---
##################################################
# RESOURCES TYPES
##################################################
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

##################################################
# RESOURCES
##################################################
resources:
- name: pipeline
  type: git
  source:
    uri: ((pipeline-git-uri))
    branch: ((pipeline-git-branch))

- name: terraform
  type: terraform
  source:
    backend_type: azurerm
    backend_config:
      resource_group_name: ((tf_resource_group_name))
      storage_account_name: ((tf_storage_account_name))
      container_name:       ((tf_container_name))
      key:                  ((tf_key))
    vars:
      astra_token: ((astra_token))
    env:
      ARM_ACCESS_KEY: ((arm_access_key))
      
##################################################
# JOBS
##################################################
jobs:
- name: terraform-plan
  plan:
  - get: pipeline
  - put: terraform
    params:
      env_name: ((tf_env_name))
      terraform_source: pipeline/terraform
      plan_only: true

- name: terraform-destroy
  plan:
    - get: pipeline
      trigger: false
      passed: [terraform-plan]
    - get: terraform
      trigger: false
      passed: [terraform-plan]
    - put: terraform
      params:
        env_name: ((tf_env_name))
        terraform_source: pipeline/terraform
        action: destroy
      get_params:
        action: destroy

- name: terraform-apply
  plan:
  - get: pipeline
    trigger: true
    passed: [terraform-plan]
  - get: terraform
    trigger: true
    passed: [terraform-plan]
  - put: terraform
    params:
      env_name: ((tf_env_name))
      terraform_source: pipeline/terraform
      plan_run: true 
      
- name: run-cql
  plan:
  - get: pipeline
    trigger: false
    passed: [terraform-apply]
  - get: terraform
    trigger: false
    passed: [terraform-apply]
  - task: run-cqlsh
    file: pipeline/concourse/tasks/cqlsh.yml
    params:
      ASTRA_CLIENT_ID: ((astra_client_id))
      ASTRA_CLIENT_SECRET: ((astra_client_secret))
      
         
