---
platform: linux

image_resource:
  type: registry-image
  source: 
    repository: datastaxdesktop/cqlsh
    tag: '1.0.1'

inputs:
- name: pipeline
- name: terraform

params:
  ASTRA_CLIENT_ID: 
  ASTRA_CLIENT_SECRET: 

run:
  path: pipeline/concourse/tasks/cqlsh.sh